### PR TITLE
Fixed tests to handle zero matching in OTP 27

### PR DESCRIPTION
**Pull request by dw-kihara**
Starting from OTP 27, `0.0` no longer matches `-0.0`, so several tests need explicit `-` signs. Also added `+` signs to suppress warnings requiring explicit `+0.0` for matching.

### CODE REVIEW

**Comment by dumbbell** [comment]
Hi! Thanks for the patch!

Could you please add the pull request description to the commit message? It is interesting and will be valuable in the Git history.

**Comment by dumbbell** [comment]
I stopped the test against Erlang 23. You can rebase your branch on top of the latest master and CI should be happy.

**Comment by dw-kihara** [comment]
> Could you please add the pull request description to the commit message? It is interesting and will be valuable in the Git history.

Added the description. Does it make sence?

**Comment by dumbbell** [comment]
> > Could you please add the pull request description to the commit message? It is interesting and will be valuable in the Git history.
> 
> Added the description. Does it make sence?

Yes :-)

I merged your patch, thank you!

**Pull request merged**
